# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fdn < Formula
  desc ""
  homepage "https://github.com/hobbymarks/fdn"
  version "0.6.9"

  on_macos do
    url "https://github.com/hobbymarks/fdn/releases/download/v0.6.9/fdn_0.6.9_darwin_all.tar.gz"
    sha256 "d47b2d44354960d9bd4e945623818d5fe13fb19cdce8c99e82070d0fecd4dc76"

    def install
      bin.install "fdn"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/fdn/releases/download/v0.6.9/fdn_0.6.9_linux_amd64.tar.gz"
      sha256 "a357f851834533e5d00f58ec4f731bad77be59edd994477b45b80ff8c547ce38"

      def install
        bin.install "fdn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/fdn/releases/download/v0.6.9/fdn_0.6.9_linux_arm64.tar.gz"
      sha256 "1e8acb3e16eac12ea68345028626feacc74889e1b2a8dbd025c9fb296d35e5e6"

      def install
        bin.install "fdn"
      end
    end
  end
end
