# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fdn < Formula
  desc ""
  homepage "https://github.com/hobbymarks/fdn"
  version "0.6.5"

  on_macos do
    url "https://github.com/hobbymarks/fdn/releases/download/v0.6.5/fdn_0.6.5_darwin_all.tar.gz"
    sha256 "f09fb7daf707b7c7caa4217f1f3685406e87058b53a5b8af01c221283c664560"

    def install
      bin.install "fdn"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/fdn/releases/download/v0.6.5/fdn_0.6.5_linux_arm64.tar.gz"
      sha256 "abb7b51c33021d276b00b0be471dbd6ec16b952d67d52e963bff6ce077779b2f"

      def install
        bin.install "fdn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/fdn/releases/download/v0.6.5/fdn_0.6.5_linux_amd64.tar.gz"
      sha256 "5c4387fb4aabdd4e083f40717fb5c076aa0ed539394e9a25306de85fc6a7713a"

      def install
        bin.install "fdn"
      end
    end
  end
end
