# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Giat < Formula
  desc ""
  homepage "https://github.com/hobbymarks/giat"
  version "0.5.7"

  on_macos do
    url "https://github.com/hobbymarks/giat/releases/download/v0.5.7/giat_0.5.7_darwin_all.tar.gz"
    sha256 "ed5e5dc5700a7b2abb658ef2203a1c2f54d21bd762c39d8d9824fd75b2edf050"

    def install
      bin.install "giat"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/giat/releases/download/v0.5.7/giat_0.5.7_linux_arm64.tar.gz"
      sha256 "3fda28ff265e5db0f3720c4ef7d3de6952b36c296ff25676f806cfacbc8316ab"

      def install
        bin.install "giat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/giat/releases/download/v0.5.7/giat_0.5.7_linux_amd64.tar.gz"
      sha256 "5065f333b7aa6161d5b0edf3d972642f6649898a29894bd9bed6b931388714dc"

      def install
        bin.install "giat"
      end
    end
  end
end
