# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Giat < Formula
  desc ""
  homepage "https://github.com/hobbymarks/giat"
  version "0.6.10"

  on_macos do
    url "https://github.com/hobbymarks/giat/releases/download/v0.6.10/giat_0.6.10_darwin_all.tar.gz"
    sha256 "5727cb155cf9d5dd05da3a4841e1d3596c2c8bb0ffffbc57bb90c313973f65b1"

    def install
      bin.install "giat"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/giat/releases/download/v0.6.10/giat_0.6.10_linux_amd64.tar.gz"
      sha256 "1a8026439dfa1ac63c1332e5c0adbca9eb94a444ff3ceae786c1e3ab82cc7791"

      def install
        bin.install "giat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/giat/releases/download/v0.6.10/giat_0.6.10_linux_arm64.tar.gz"
      sha256 "fb646caa5a09880bc595840ef54fdbd170e6d73cbcab6d651f6f2e3aa1a847cd"

      def install
        bin.install "giat"
      end
    end
  end
end
