# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Giat < Formula
  desc ""
  homepage "https://github.com/hobbymarks/giat"
  version "0.5.7"

  on_macos do
    url "https://github.com/hobbymarks/giat/releases/download/v0.5.7/giat_0.5.7_darwin_all.tar.gz"
    sha256 "9432e359c4fd2d700afe20b9d1b0b4eb27b9e2c48198c49793887183fd4435ef"

    def install
      bin.install "giat"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/giat/releases/download/v0.5.7/giat_0.5.7_linux_amd64.tar.gz"
      sha256 "2b5ec023b5c1e183e9938bb4138e5a15952e708012c8e12b661e0d721464eb09"

      def install
        bin.install "giat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/giat/releases/download/v0.5.7/giat_0.5.7_linux_arm64.tar.gz"
      sha256 "5cbb07ce94ddaa381f5a8973cf4bb9be045df72015c9e9d01d3c32b0f9dcb5ea"

      def install
        bin.install "giat"
      end
    end
  end
end
