# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobar < Formula
  desc ""
  homepage "https://github.com/hobbymarks/gobar"
  version "0.0.1"

  on_macos do
    url "https://github.com/hobbymarks/gobar/releases/download/v0.0.1/gobar_0.0.1_darwin_all.tar.gz"
    sha256 "474de26e5a1d357d437d440653b5725b419b79bcd2190f3e99a7ec5308df031f"

    def install
      bin.install "gobar"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/gobar/releases/download/v0.0.1/gobar_0.0.1_linux_amd64.tar.gz"
      sha256 "accd98ac48b3de96aa55d46f13f4f3108efd27d7905d1bf1eaa5d824d68399cc"

      def install
        bin.install "gobar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/gobar/releases/download/v0.0.1/gobar_0.0.1_linux_arm64.tar.gz"
      sha256 "a62c3bf065c16d3512c23a2f110a357c61de70889dfa43975ce4520dd8fca205"

      def install
        bin.install "gobar"
      end
    end
  end
end
