# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohash < Formula
  desc ""
  homepage "https://github.com/hobbymarks/gohash"
  version "0.7.0"

  on_macos do
    url "https://github.com/hobbymarks/gohash/releases/download/v0.7.0/gohash_0.7.0_darwin_all.tar.gz"
    sha256 "ec8a316141ebdce76cc62be94e0c80472c25db8d6f78a51aa2ca9811ac53adbb"

    def install
      bin.install "gohash"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/gohash/releases/download/v0.7.0/gohash_0.7.0_linux_arm64.tar.gz"
      sha256 "ea3ce937340354a18418bac8cd06d38860bdc40eae35b797a24449d6591af0b4"

      def install
        bin.install "gohash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/gohash/releases/download/v0.7.0/gohash_0.7.0_linux_amd64.tar.gz"
      sha256 "5a7c161aec6a9471aa8b99be47ed4ebabccff476750e0e9e41bb35ab3ed2900a"

      def install
        bin.install "gohash"
      end
    end
  end
end
