# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ResCciGo < Formula
  desc ""
  homepage "https://github.com/hobbymarks/res_cci_go"
  version "0.0.1"

  on_macos do
    url "https://github.com/hobbymarks/res_cci_go/releases/download/v0.0.1/res_cci_go_0.0.1_darwin_all.tar.gz"
    sha256 "e9ef86371e9018d4988676dd3bea97be4e22dac059c2cfcda95428096357457d"

    def install
      bin.install "res_cci_go"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/res_cci_go/releases/download/v0.0.1/res_cci_go_0.0.1_linux_arm64.tar.gz"
      sha256 "7aa6cebf5d56dbc1e6f9656c08e78a394639dd9f2ae84e24ed2a5f5ff3e1f0f0"

      def install
        bin.install "res_cci_go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/res_cci_go/releases/download/v0.0.1/res_cci_go_0.0.1_linux_amd64.tar.gz"
      sha256 "b875bf788f846ce96be453d73fde3dc18760453e7f7f51335db170e02e1b4814"

      def install
        bin.install "res_cci_go"
      end
    end
  end
end
